package com.castIRL.ui.theme

import androidx.compose.ui.graphics.Color

// Brand fallback palette — generated from seed #0F4334 (M3 tonal system)
// Used on Android < 12 where dynamic color isn't available.

// Dark scheme
val DarkPrimary             = Color(0xFF73D8A5)
val DarkOnPrimary           = Color(0xFF003921)
val DarkPrimaryContainer    = Color(0xFF00522F)
val DarkOnPrimaryContainer  = Color(0xFF90F5BF)
val DarkSecondary           = Color(0xFFB3CCBB)
val DarkOnSecondary         = Color(0xFF1F352A)
val DarkSecondaryContainer  = Color(0xFF354B40)
val DarkOnSecondaryContainer= Color(0xFFCFE9D7)
val DarkTertiary            = Color(0xFFA1CDD2)
val DarkOnTertiary          = Color(0xFF00373C)
val DarkTertiaryContainer   = Color(0xFF1F4E54)
val DarkOnTertiaryContainer = Color(0xFFBDEAEF)
val DarkError               = Color(0xFFFFB4AB)
val DarkOnError             = Color(0xFF690005)
val DarkErrorContainer      = Color(0xFF93000A)
val DarkOnErrorContainer    = Color(0xFFFFDAD6)
val DarkBackground          = Color(0xFF0F1510)
val DarkOnBackground        = Color(0xFFDFE4DE)
val DarkSurface             = Color(0xFF0F1510)
val DarkOnSurface           = Color(0xFFDFE4DE)
val DarkSurfaceVariant      = Color(0xFF404943)
val DarkOnSurfaceVariant    = Color(0xFFBFC9C2)
val DarkOutline             = Color(0xFF8A938C)
val DarkOutlineVariant      = Color(0xFF404943)
val DarkSurfaceContainerLowest = Color(0xFF0A100C)
val DarkSurfaceContainerLow    = Color(0xFF171E19)
val DarkSurfaceContainer       = Color(0xFF1A211C)
val DarkSurfaceContainerHigh   = Color(0xFF242B25)
val DarkSurfaceContainerHighest= Color(0xFF2F362F)
val DarkSurfaceBright          = Color(0xFF353B35)
val DarkSurfaceDim             = Color(0xFF0F1510)

// Light scheme
val LightPrimary             = Color(0xFF006C3E)
val LightOnPrimary           = Color(0xFFFFFFFF)
val LightPrimaryContainer    = Color(0xFF9CF5BD)
val LightOnPrimaryContainer  = Color(0xFF002111)
val LightSecondary           = Color(0xFF4E6356)
val LightOnSecondary         = Color(0xFFFFFFFF)
val LightSecondaryContainer  = Color(0xFFD0E8D8)
val LightOnSecondaryContainer= Color(0xFF0B1F15)
val LightTertiary            = Color(0xFF3A6568)
val LightOnTertiary          = Color(0xFFFFFFFF)
val LightTertiaryContainer   = Color(0xFFBDEAEF)
val LightOnTertiaryContainer = Color(0xFF002022)
val LightError               = Color(0xFFBA1A1A)
val LightOnError             = Color(0xFFFFFFFF)
val LightErrorContainer      = Color(0xFFFFDAD6)
val LightOnErrorContainer    = Color(0xFF410002)
val LightBackground          = Color(0xFFF5FBF4)
val LightOnBackground        = Color(0xFF171D18)
val LightSurface             = Color(0xFFF5FBF4)
val LightOnSurface           = Color(0xFF171D18)
val LightSurfaceVariant      = Color(0xFFDCE5DC)
val LightOnSurfaceVariant    = Color(0xFF404943)
val LightOutline             = Color(0xFF6D7770)
val LightOutlineVariant      = Color(0xFFBFC9C2)
val LightSurfaceContainerLowest = Color(0xFFFFFFFF)
val LightSurfaceContainerLow    = Color(0xFFEFF5EF)
val LightSurfaceContainer       = Color(0xFFE8F4EC)
val LightSurfaceContainerHigh   = Color(0xFFE2EEE6)
val LightSurfaceContainerHighest= Color(0xFFDCE8DF)
val LightSurfaceBright          = Color(0xFFF5FBF4)
val LightSurfaceDim             = Color(0xFFD6E3D7)
